stackitcloud/gardener

pkg/component/etcd/bootstrap.go
pkg/component/etcd/bootstrap_test.go
pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks-copy.yaml
pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds-copy.yaml

We will keep the migration code for our gardener release that ensures that the migration of the etcd CRDs from a `ManagedResource` to directly applied code happens without actually deleting the CRDs. Because we don't use v1.72 as a stepping stone
Required as we don't use v1.72
Fixes Removal of CRD by MR
* Workaround removed in https://github.com/gardener/gardener/pull/8022
* Changes introduced in https://github.com/gardener/gardener/pull/8002
```other operator
```

fix: Revert "Cleanup TODO (#8022)"

---

extensions/pkg/controller/worker/genericactuator/actuator_delete.go
extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
extensions/pkg/controller/worker/helper/helper.go
pkg/operation/care/health.go

/area ops-productivity
/kind regression
/hold wait-for-testing
In Gardener 1.76 the `Generic_Actuator` gets an errCodeFunction which becomes aware of any provider errors. Before this gardener version this do not happen. Somewhere in the rework of the error detection something wasn't implemented correctly or got lost. It's unclear as to specific what but once we have atleast gardener 1.76+ the funtionality should become available again.
The openstack extension is aware of the errCodeFunction since v1.37
This PR hotfixxes the missing errCodeFunction directly into gardener/gardener instead of being implemented by the extension. Therefore we must remove later-on.
**This PR is not mergable upstream.**
**Which issue(s) this …

fix gardener not setting ErrorCode on infra error

---

pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go

/kind bug
/hold WIP
Testing this change on ondemand `ond-70a1f0`: https://github.com/stackitcloud/ske-base/pull/514:
r-seed started, s-seed is also starting

Remove Dependency of OperatingSystemConfig on Extensions

---

pkg/operation/care/seed_health.go

This can be removed with gardener v1.85.0
/kind bug
https://github.com/gardener/gardener/pull/8240/files#diff-ca1fef8bef9452102c66af817d137a2bd5dbcaf2368d4cf0983c0f208b99ecedR130 added the vali managed resources to the health checks of a seed. Since we explicitly disable vail in the gardenlet values https://github.com/stackitcloud/ske-base/blob/main/base/installer/config/gardenlet-values-0.yaml#L95 this can never work.
In https://github.com/gardener/gardener/pull/8387 (v1.79.0) the care package was refactored and the change needs to be applied to `pkg/gardenlet/controller/seed/care/health.go` instead
This is later fixed in https://github.com/gardener/gardener/pull/8840, so with g/g 1.85.x this commit can be dropped. …

Remove vali check for Seed Health

---

pkg/resourcemanager/controller/managedresource/reconciler.go
pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
third_party/controller-runtime/pkg/apiutil/lazyrestmapper.go

/area control-plane
/kind bug
do not fail if hvpa CRD is not deployed.
After upgrading to 1.79 all seeds became stuck in `[task "sync StatefulSet task" failed: admission webhook "high-availability-config.resources.gardener.cloud" denied the request: failed to list all HVPAs: failed to get API group resources: unable to retrieve the complete list of server APIs: autoscaling.k8s.io/v1alpha1: the server could not find the requested resource])`.
Replaces #47 as that branch used the wrong base commit.

resourcemanager: do not fail if hvpa CRD is not deployed

---

pkg/component/etcd/etcd.go
pkg/component/etcd/etcd_test.go
pkg/operation/botanist/etcd.go
pkg/operator/controller/garden/garden/reconciler_reconcile.go

Cherrypick of https://github.com/gardener/gardener/pull/8795. This fixes (most) cases of stuck credentials rotations.
The cherry-picked changes are part of Gardener 1.84 and can be removed once we reach that version.

Fix unrecoverable issues with `etcd` during credentials rotation (#8795)

---

docs/deployment/feature_gates.md
imagevector/images.yaml
pkg/component/apiserverproxy/apiserver_proxy.go
pkg/component/apiserverproxy/apiserver_proxy_test.go
pkg/component/apiserverproxy/templates/envoy.yaml.tpl
pkg/component/kubeapiserverexposure/kube_apiserver_sni.go
pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go
pkg/features/features.go
pkg/gardenlet/controller/seed/seed/components.go
pkg/gardenlet/features/features.go
pkg/operation/botanist/kubeapiserverexposure.go

Cherry-pick of https://github.com/stackitcloud/gardener/tree/hackathon-apiserver-proxy
TODO
Part of [ADO#626304](https://dev.azure.com/schwarzit/schwarzit.ske/_workitems/edit/626304)
```other operator
```

[ske-v1.86] Cherry-pick apiserver-proxy changes

---

docs/deployment/feature_gates.md
imagevector/images.yaml
pkg/component/apiserverproxy/apiserver_proxy.go
pkg/component/apiserverproxy/apiserver_proxy_test.go
pkg/component/apiserverproxy/templates/envoy.yaml.tpl
pkg/component/kubeapiserverexposure/kube_apiserver_sni.go
pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go
pkg/features/features.go
pkg/gardenlet/controller/seed/seed/components.go
pkg/gardenlet/features/features.go
pkg/operation/botanist/kubeapiserverexposure.go

Cherry-pick of https://github.com/stackitcloud/gardener/tree/hackathon-apiserver-proxy
TODO
Part of [ADO#626304](https://dev.azure.com/schwarzit/schwarzit.ske/_workitems/edit/626304)
```other operator
```

[ske-v1.87] Cherry-pick apiserver-proxy changes

---

pkg/apis/core/validation/project.go

During the gardener-operator migration, the `garden` namespaces creator will be changed, which is not allowed by the validation. We need to allow this change for the migration to work successfully.
https://dev.azure.com/schwarzit/schwarzit.ske/_workitems/edit/647586
**Notes**
Im adding this to 1.91, as I assume we'll upgrade to that today.
@robinschneider this needs to be added to #82 as well.

Allow changing the project creator of the "garden" project

---

pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets.go
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets_test.go

Backport https://github.com/gardener/gardener/pull/9723
This is not needed for G/G 1.92+ (already included)
Because, well the OSC Config is updated on every reconcile which is annoying and makes reconciles super long.
Fixes #
```other operator
```

[v1.90] Omit useless data from `OperatingSystemConfig` in `Secret`s reconciled by `gardener-node-agent` (#9723)

---

pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets.go
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets_test.go

Backport https://github.com/gardener/gardener/pull/9723
This is not needed for G/G 1.92+ (already included)
Because, well the OSC Config is updated on every reconcile which is annoying and makes reconciles super long.
Fixes #
```other operator
```

[v1.91] Omit useless data from `OperatingSystemConfig` in `Secret`s reconciled by `gardener-node-agent` (#9723)

---

pkg/apis/core/validation/seed.go

Temporarily allow this change. Because we want to allign the CIDRs used. Let's see what this breaks...

Allow changing networks of stackit seed (for migration)

---

cmd/gardener-operator/app/app.go
pkg/operator/metrics/garden.go
pkg/operator/metrics/garden_test.go
pkg/operator/metrics/metrics.go
pkg/operator/metrics/metrics_suite_test.go
skaffold-operator.yaml

This will not be published upstream, see: https://github.com/gardener/gardener/pull/10314
There is an ongoing effort to export CustomResourceMetrics via kube-state-metrics, which we want to switch to once that is available.
This change can be dropped when this is available, probably after at least v1.103
https://dev.azure.com/schwarzit/schwarzit.ske/_workitems/edit/656573

Collect garden condition metrics

---

pkg/apis/core/validation/project.go
pkg/apis/core/validation/seed.go

/kind cleanup
Reverts changes that were needed only for the operator migration
Selected `merge-method-rebase`, so that it is hopefully clear for g/g 1.96 which commits can be dropped.
https://dev.azure.com/schwarzit/schwarzit.ske/_workitems/edit/663702

Drop migration changes

---

Makefile

/kind bug
The Gardener Makefile relies on a set of tools. The binaries of those tools are expected in the directory `hack/tools/bin/linux-<arch>`. 
If a tool binary is missing, the mechanics of the Make tool are used to trigger a download of the binary from the internet: There is a make target for each tool, which executes the download. All other make targets define dependencies on the "tool targets" for the tools they are using.
The Gardener integration tests use the `helm` tool, hence the corresponding make target `test-integration` should depend on the `$(HELM)` tool target, which will make sure the `helm` binary is available.
As far as I understand, the dependency on helm in the integration tests was introduced …

`test-integration` should depend on `$(HELM)`

---

pkg/apis/core/validation/backupbucket.go
pkg/apis/core/validation/seed.go
pkg/apis/extensions/validation/backupbucket.go
pkg/apis/extensions/validation/backupentry.go

We want to move to the backup-s3 provider because it supports customCa and means we have less code to maintain. The field is immutable. In our case it should be fine, because the stackit provider is essentially just S3.
As far as I can tell, the `BackupEntry` does not deny this change.
~~/hold I want to test the prerelease on ondemand~~ DONE

Allow changing backup provider to S3

---

pkg/apis/core/validation/seed.go
pkg/apis/core/validation/seed_test.go

Backupbuckets on STACKIT:X QA were created in region `eu01` which is immutable. This PR allows the user to change the seed Configuration so we can delete & recreate backupbuckets and entries in the correct region for STACKIT:X which is `object-storage`
Fixes #

Allow to change `seedSpec.backup.region` for STACKIT:X region migration

---

pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/cadvisor.yaml
pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/kubelet.yaml
pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs_test.go

/kind bug
Since Prometheus Targets are all down due to [gardener#9716](https://github.com/gardener/gardener/pull/9716) in Gardener v1.96, we need to set insecure_skip_verify to true on cadvisor & kubelet scrape config.
This is only a temporary fix, it can be dropped whenever we have a long term solution, which would likely involve enabling server certificate bootstrap (instead of self signed certificates) for the kubelet

Set `insecure_skip_verify` to true for cadvisor and kubelet job

---

pkg/component/extensions/operatingsystemconfig/original/components/containerd/component.go
pkg/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
skaffold-operator.yaml
skaffold.yaml

This reverts commit b88242d3f7d9e71818389843acf8d632bdff5fb9.
/area os
/kind bug
Reverting this as this will stop the gardener-node-agent from deleting our custom containerd system override.
This PR can potentially be dropped with v111 (if verified that it works) due to https://github.com/gardener/gardener/pull/11015
Fixes #
```other operator
```

Workaround: Gardener Node Agent deletes containerd drop-in

---

pkg/component/networking/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
pkg/component/networking/istio/test_charts/ingress_vpn_envoy_filter.yaml

/area networking
/area security
Implementation of https://github.com/gardener/gardener/pull/11328 for our fork.
Our fork needs to implement a different header regex from upstream, bcs. otherwise our forked apiserver-proxy would break.
This will inevitably lead to merge / cherry-pick conflicts!
In this case, our version of the regex should be kept until https://github.com/gardener/gardener/issues/11214 is fully implemented and released.
Preparation for https://github.com/gardener/gardener/issues/11214
The "reversed-vpn-auth-server" deployment will be removed later on from upstream.
```noteworthy operator
Incoming …
```

Drop usage of ext-authz-server

---

cmd/gardenlet/app/migration.go
pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
pkg/component/extensions/operatingsystemconfig/nodeinit/templates/scripts/init.tpl.sh
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
pkg/component/gardener/apiserver/apiserver_test.go
pkg/component/gardener/apiserver/deployment.go
pkg/component/gardener/controllermanager/configmaps.go
pkg/component/gardener/controllermanager/controller_manager_test.go
pkg/component/gardener/resourcemanager/resource_manager.go
pkg/component/gardener/resourcemanager/resource_manager_test.go
pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/cadvisor.yaml
pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/kubelet.yaml
pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs_test.go
pkg/component/shared/resourcemanager.go
pkg/component/shared/resourcemanager_test.go

**Dropped Commits**
- [[ske-v1.88] cherrypick apiserver-proxy changes](https://github.com/stackitcloud/gardener/pull/127/commits/d2224e1a6fed0f207dd3a8f290f23201394bf6d4#diff-0cc11d98580d91dba21a3bd4c309844de9e80091c46f4e7ce4324ecd9d0aba51)
- A new introduced `RemoveAPIServerProxyLegacyPort` now handles this
- [Allow configuring a maximum node count per shoot (https://github.com/stackitcloud/gardener/pull/124)](https://github.com/stackitcloud/gardener/pull/127/commits/5375f14515da314321f079e0261cd94491cd2707)
- https://github.com/gardener/gardener/pull/11279 is included now
- https://github.com/stackitcloud/gardener/pull/125 
- https://github.com/gardener/gardener/pull/11328 is included now

:cherries: Cherry-Picks for `v1.113.0`

---

go.mod
pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
pkg/component/extensions/operatingsystemconfig/nodeinit/templates/scripts/init.tpl.sh
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
pkg/component/gardener/apiserver/apiserver_test.go
pkg/component/gardener/apiserver/deployment.go
pkg/component/gardener/controllermanager/configmaps.go
pkg/component/gardener/controllermanager/controller_manager_test.go
pkg/component/gardener/resourcemanager/resource_manager.go
pkg/component/gardener/resourcemanager/resource_manager_test.go
pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/cadvisor.yaml
pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/kubelet.yaml
pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs_test.go
pkg/component/shared/resourcemanager.go
pkg/component/shared/resourcemanager_test.go
pkg/operator/controller/extension/required/runtime/add_test.go
pkg/utils/gardener/garden.go
pkg/utils/gardener/garden_test.go
test/integration/operator/extension/required/runtime/runtime_test.go

/area open-source
This PR applies our fork changes to the Gardener 1.115 release.

v1.115.0 cherry-picks

---

pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
pkg/component/extensions/operatingsystemconfig/nodeinit/templates/scripts/init.tpl.sh
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
pkg/component/gardener/apiserver/apiserver_test.go
pkg/component/gardener/apiserver/deployment.go
pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/cadvisor.yaml
pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/kubelet.yaml
pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs_test.go
pkg/component/shared/resourcemanager.go
pkg/component/shared/resourcemanager_test.go
pkg/operator/controller/extension/required/runtime/add_test.go
pkg/utils/gardener/operator/garden.go
pkg/utils/gardener/operator/garden_test.go
test/integration/operator/extension/required/runtime/runtime_test.go

/label tide/merge-method-rebase
This PR applies our fork changes to the Gardener 1.118.0 release.
Umbrella Issue: https://github.com/stackitcloud/ske-base/issues/2848

v1.118.0 cherry-picks

---

pkg/component/shared/resourcemanager.go
pkg/component/shared/resourcemanager_test.go

/kind cleanup
This reverts commit cdb3a8ac0af3fcfc44dd4b7987dae479e48312fe.
Replaced by improved kyverno policies with proper background scanning/mutating. This commit can be dropped along with its original commit when upgrading to g/g@v1.119.
Fixes #
/hold until verified in ondemand

Revert "Enable AlwaysUpdate for resource manager targeting runtime cluster"

---

pkg/apis/operator/v1alpha1/validation/garden.go
pkg/apis/operator/v1alpha1/validation/garden_test.go
pkg/operator/controller/extension/required/runtime/add_test.go
pkg/utils/gardener/operator/garden.go
pkg/utils/gardener/operator/garden_test.go
test/integration/operator/extension/required/runtime/runtime_test.go

How to categorize this PR?
What this PR does / why we need it:
This PR reverts the last remaining patch in our fork.
Which issue(s) this PR fixes:
Fixes [JIRA#STACKITSKE-830](https://jira.schwarz/browse/STACKITSKE-830)
Special notes for your reviewer:
After rolling out this version of our fork, we still need to patch the `gardens.operator.gardener.cloud` CRD as updating the bucket name is still forbidden by https://github.com/stackitcloud/gardener/blob/13bbc31080c9e2ec736eb48a5d683938ea56d8fc/pkg/apis/operator/v1alpha1/types_garden.go#L287C1-L287C10
We currently pull CRDs from upstream, so no way we can fix this in this repository.

Allow Operator to manage ETCd `BackupBucket`
